version: "3.9"

services:
  public-api-service:
    build:
      context: ./api
      dockerfile: Dockerfile.public.developnment
    volumes:
      - ./api:/app
      - /app/node_modules/
  private-api-service:
    build:
      context: ./api
      dockerfile: Dockerfile.private.developnment
    volumes:
      - ./api:/app
      - /app/node_modules/
  connect-service:
    build:
      context: ./connect
      dockerfile: Dockerfile.developnment
    volumes:
      - ./connect:/app
      - /app/node_modules/
    depends_on:
      - private-api-service
  proxy:
    build:
      context: ./.nginx
      dockerfile: Dockerfile.developnment
    depends_on:
      - public-api-service
      - connect-service
    ports:
      - "3333:8080"
  redis:
    build:
      context: ./.redis
      dockerfile: Dockerfile.developnment
    volumes:
      - .redis/data:/data
    ports:
      - 6379:6379
