version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.developnment
    volumes:
      - ./web:/app
      - /app/node_modules/
    ports:
      - "9229:9229"
  proxy:
    build:
      context: ./.nginx
      dockerfile: Dockerfile.developnment
    volumes:
      - ./.nginx/templates:/etc/nginx/templates
    depends_on:
      - web
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=3333
    ports:
      - "3333:3333"
  redis:
    build:
      context: ./.redis
      dockerfile: Dockerfile.developnment
    volumes:
      - .redis/data:/data
    ports:
      - 6379:6379
