version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.developnment
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - "9229:9229"
  proxy:
    build:
      context: ./.nginx
      dockerfile: Dockerfile.developnment
    depends_on:
      - web
    ports:
      - "3030:8080"
