version: "3.9"

services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile.developnment
    volumes:
      - ./api:/app
      - /app/node_modules/
    ports:
      - "3131:3131"
  connect-service:
    build:
      context: ./connect
      dockerfile: Dockerfile.developnment
    volumes:
      - ./connect:/app
      - /app/node_modules/
    ports:
      - "3030:3030"
  proxy:
    build:
      context: ./.nginx
      dockerfile: Dockerfile.developnment
    depends_on:
      - api-service
      - connect-service
    ports:
      - "3333:8080"
  redis:
    build:
      context: ./.redis
      dockerfile: Dockerfile.developnment
    volumes:
      - .redis/data:/data
    ports:
      - 6379:6379
