FROM node:16.7-alpine as BUILD

WORKDIR /app/

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:16.7-alpine

WORKDIR /app/

ENV PORT=8080

ENV PUBLIC=true

EXPOSE ${PORT}

COPY --from=BUILD /app/dist /app/dist/

COPY package.json .

RUN npm install --production

CMD ["npm", "run", "start"]  